# Generated by Django 4.2.5 on 2023-10-30 15:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_task_lastadded"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="lastAdded",
            new_name="last_added",
        ),
    ]
