# Generated by Django 4.2.5 on 2023-10-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_rename_lastadded_task_last_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="last_added",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
