# Generated by Django 4.2.5 on 2023-10-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_task_last_added"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="last_added",
        ),
        migrations.AddField(
            model_name="todo",
            name="last_added",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
