# Generated by Django 4.2.5 on 2023-10-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_remove_task_last_added_todo_last_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="task",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
