# Generated by Django 4.2.5 on 2023-11-14 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_task_ordering_todo_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="last_added",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
